version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: postgres:9.6.2
    steps:
      - checkout
      - setup_remote_docker
      - run: ./gradlew test --info
